name: Run PHPUnit Tests

on:
  push:
    branches: [CI/launch_test]
  pull_request:
    branches: [CI/launch_test]

jobs:
  phpunit:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: [8.4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          extensions: mbstring, mysqli, pdo, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Dump Autoload
        run: composer dump-autoload -o

      - name: Run PHPUnit with Coverage
        run: vendor/bin/phpunit --configuration phpunit.xml --coverage-text
