name: Run PHPUnit Tests

on:
  push:
    branches: [main , integration/tdd]
  pull_request:
    branches: [main , integration/tdd]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.4]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          extensions: mbstring, mysqli, pdo, pdo_mysql

      - name: Validate composer.json
        run: composer validate --strict || true   # permet de continuer mÃªme avec warnings

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Dump autoload
        run: composer dump-autoload

      - name: Run PHPUnit
        run: vendor/bin/phpunit --configuration phpunit.xml
